name: EduVault

services:
  eduvault:
    container_name: App_EduVault
    image: ${DOCKER_REGISTRY-}eduvault
    build:
      context: .
      dockerfile: EduVault/Dockerfile
    environment:
      - ConnectionStrings__PostgresDocker=Host=postgresql;Port=5432;Database=EduVault;Username=postgres;Password=1Qwerty;
      - ConnectionStrings__MongoDocker=mongodb://mongo:1Qwerty@mongodb:27017/EduVault?authSource=admin
    depends_on:
      - postgresql
      - mongodb
    networks:
      - app-network

  postgresql:
    container_name: DB_PostgreSQL
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=EduVault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1Qwerty
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongodb:
    container_name: DB_Mongo
    ports:
     - "27017:27017"
    environment:
     - MONGO_INITDB_DATABASE=EduVault
     - MONGO_INITDB_ROOT_USERNAME=mongo
     - MONGO_INITDB_ROOT_PASSWORD=1Qwerty
    volumes:
     - mongodb_data:/data/db
    image: mongo
    networks:
      - app-network
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pgdata
  mongodb_data:
    
networks:
  app-network:
    driver: bridge
   